using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared._Misfits.PipBoy;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PipBoy;

[GenerateTypedNameReferences]
public sealed partial class PipBoyFactionUiFragment : BoxContainer
{
    private const int UnassignedTaskId = -1;
    private readonly List<uint?> _taskAssignees = new();
    private PipBoyHubUiState? _lastState;
    private string _memberSearch = string.Empty;

    public event Action<PipBoyHubMessageType, uint?, uint?, string?>? OnSendMessage;

    public PipBoyFactionUiFragment()
    {
        RobustXamlLoader.Load(this);

        FactionTabs.SetTabTitle(0, Loc.GetString("pipboy-faction-tab-roster"));
        FactionTabs.SetTabTitle(1, Loc.GetString("pipboy-faction-tab-announcements"));
        FactionTabs.SetTabTitle(2, Loc.GetString("pipboy-faction-tab-general"));
        FactionTabs.SetTabTitle(3, Loc.GetString("pipboy-faction-tab-tasks"));

        FactionSendBtn.OnPressed += _ => SendFactionMessage(false);
        FactionAnnounceBtn.OnPressed += _ => SendFactionMessage(true);
        FactionMessageInput.OnTextEntered += _ => SendFactionMessage(false);
        FactionTaskCreateBtn.OnPressed += _ => CreateTask();
        FactionTaskInput.OnTextEntered += _ => CreateTask();
        FactionMemberSearch.OnTextChanged += args =>
        {
            _memberSearch = args.Text.Trim();
            if (_lastState != null)
                RefreshRoster(_lastState);
        };
    }

    private void SendFactionMessage(bool announcement)
    {
        if (string.IsNullOrWhiteSpace(FactionMessageInput.Text))
            return;

        OnSendMessage?.Invoke(
            announcement ? PipBoyHubMessageType.FactionSendAnnouncement : PipBoyHubMessageType.FactionSendMessage,
            null,
            null,
            FactionMessageInput.Text);

        FactionMessageInput.Text = string.Empty;
    }

    private void CreateTask()
    {
        if (string.IsNullOrWhiteSpace(FactionTaskInput.Text))
            return;

        var content = FactionTaskInput.Text;
        var assigneeId = FactionTaskAssignee.SelectedId;
        if (assigneeId >= 0 && assigneeId < _taskAssignees.Count && _taskAssignees[assigneeId] is { } assigneeNumber)
            content = $"{content}\0{assigneeNumber}";

        OnSendMessage?.Invoke(PipBoyHubMessageType.FactionCreateTask, null, null, content);
        FactionTaskInput.Text = string.Empty;
        FactionTaskAssignee.SelectId(0);
    }

    public void UpdateState(PipBoyHubUiState state)
    {
        _lastState = state;
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";

        var locked = state.IsLocked;
        LockedLabel.Visible = locked;
        MainPanel.Visible = !locked;
        if (locked)
            return;

        var hasFaction = !string.IsNullOrWhiteSpace(state.FactionName);
        UnavailableLabel.Visible = !hasFaction;
        FactionPanel.Visible = hasFaction;
        TitleLabel.Text = hasFaction ? state.FactionName! : Loc.GetString("pipboy-faction-program-name");

        if (!hasFaction)
            return;

        FactionAnnounceBtn.Disabled = !state.CanFactionAnnounce;
        FactionTaskCreateBtn.Disabled = !state.CanFactionAnnounce;
        FactionTaskAssignee.Disabled = !state.CanFactionAnnounce;

        RefreshTaskAssignees(state);
        RefreshRoster(state);
        RefreshAlerts(state);
        RefreshMessages(state);
        RefreshTasks(state);
    }

    private void RefreshTaskAssignees(PipBoyHubUiState state)
    {
        _taskAssignees.Clear();
        FactionTaskAssignee.Clear();

        _taskAssignees.Add(null);
        FactionTaskAssignee.AddItem(Loc.GetString("pipboy-faction-task-unassigned"), 0);

        var index = 1;
        foreach (var member in state.FactionRoster)
        {
            _taskAssignees.Add(member.Number);
            FactionTaskAssignee.AddItem($"{member.Name} #{member.Number:D4}", index++);
        }

        if (FactionTaskAssignee.ItemCount > 0)
            FactionTaskAssignee.SelectId(0);
    }

    private void RefreshAlerts(PipBoyHubUiState state)
    {
        FactionAlertsList.RemoveAllChildren();

        if (state.FactionAlerts.Count == 0)
        {
            FactionAlertsList.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-faction-alerts-none"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        foreach (var alert in state.FactionAlerts)
        {
            var card = new PanelContainer
            {
                StyleClasses = { "AngleRect" },
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
            };

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(6),
            };

            var header = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            header.AddChild(new Label
            {
                Text = $"[{alert.Timestamp:hh\\:mm}] {alert.Message}",
                StyleClasses = { "LabelDanger" },
                HorizontalExpand = true,
                ClipText = true,
            });

            if (state.CanFactionAnnounce)
            {
                var ackButton = new Button
                {
                    Text = Loc.GetString("pipboy-faction-alert-ack"),
                    MinSize = new Vector2(56, 0),
                    Margin = new Thickness(4, 0, 0, 0),
                };
                var alertId = alert.Id;
                ackButton.OnPressed += _ => OnSendMessage?.Invoke(
                    PipBoyHubMessageType.FactionAcknowledgeAlert,
                    null,
                    null,
                    alertId.ToString());
                header.AddChild(ackButton);
            }

            row.AddChild(header);
            row.AddChild(new Label
            {
                Text = $"{Loc.GetString("pipboy-faction-location-label")}: {alert.LocationName}",
                StyleClasses = { "LabelSubText" },
                ClipText = true,
            });

            card.AddChild(row);
            FactionAlertsList.AddChild(card);
        }
    }

    private void RefreshRoster(PipBoyHubUiState state)
    {
        FactionRosterGrid.RemoveAllChildren();

        var filteredMembers = new List<PipBoyFactionMember>();
        foreach (var member in state.FactionRoster)
        {
            if (string.IsNullOrWhiteSpace(_memberSearch))
            {
                filteredMembers.Add(member);
                continue;
            }

            var search = _memberSearch;
            if (member.Name.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                $"{member.Number:D4}".Contains(search, StringComparison.OrdinalIgnoreCase) ||
                (member.JobTitle?.Contains(search, StringComparison.OrdinalIgnoreCase) ?? false) ||
                member.LocationName.Contains(search, StringComparison.OrdinalIgnoreCase))
            {
                filteredMembers.Add(member);
            }
        }

        if (filteredMembers.Count == 0)
        {
            FactionRosterGrid.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-faction-members-none"),
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
            });
            FactionRosterGrid.AddChild(new BoxContainer());
            return;
        }

        foreach (var member in filteredMembers)
        {
            var card = new PanelContainer
            {
                StyleClasses = { "AngleRect" },
                HorizontalExpand = true,
            };

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(6),
            };

            row.AddChild(new Label
            {
                Text = $"{member.Name} #{member.Number:D4}",
                HorizontalExpand = true,
                ClipText = true,
            });

            if (!string.IsNullOrWhiteSpace(member.JobTitle))
            {
                row.AddChild(new Label
                {
                    Text = member.JobTitle,
                    StyleClasses = { "LabelSubText" },
                    ClipText = true,
                });
            }

            row.AddChild(new ProgressBar
            {
                MinValue = 0f,
                MaxValue = 1f,
                Value = member.Health,
                HorizontalExpand = true,
                MinSize = new Vector2(0, 8),
                Margin = new Thickness(0, 1, 0, 1),
            });

            row.AddChild(new Label
            {
                Text = GetMemberStatusLine(member),
                StyleClasses = { "LabelSubText" },
                ClipText = true,
            });

            card.AddChild(row);
            FactionRosterGrid.AddChild(card);
        }

        if (filteredMembers.Count % 2 != 0)
            FactionRosterGrid.AddChild(new BoxContainer());
    }

    private void RefreshMessages(PipBoyHubUiState state)
    {
        FactionAnnouncementsList.RemoveAllChildren();
        FactionGeneralList.RemoveAllChildren();

        var hasAnnouncements = false;
        var hasGeneral = false;
        foreach (var message in state.FactionMessages)
        {
            var targetList = message.IsAnnouncement ? FactionAnnouncementsList : FactionGeneralList;
            var prefix = message.IsAnnouncement
                ? Loc.GetString("pipboy-faction-announcement-prefix")
                : Loc.GetString("pipboy-faction-comms-prefix");

            var card = new PanelContainer
            {
                StyleClasses = { "AngleRect" },
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
            };

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(6),
            };

            row.AddChild(new Label
            {
                Text = $"[{message.Timestamp:hh\\:mm}] {prefix} {message.SenderName}",
                StyleClasses = { "LabelSubText" },
                ClipText = true,
            });
            row.AddChild(new Label
            {
                Text = message.Content,
                HorizontalExpand = true,
                ClipText = true,
            });

            card.AddChild(row);
            targetList.AddChild(card);
            hasAnnouncements |= message.IsAnnouncement;
            hasGeneral |= !message.IsAnnouncement;
        }

        if (!hasAnnouncements)
        {
            FactionAnnouncementsList.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-faction-announcements-none"),
                StyleClasses = { "LabelSubText" },
            });
        }

        if (!hasGeneral)
        {
            FactionGeneralList.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-faction-general-none"),
                StyleClasses = { "LabelSubText" },
            });
        }

        FactionAnnouncementsScroll.SetScrollValue(new Vector2(0, float.MaxValue));
        FactionGeneralScroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private void RefreshTasks(PipBoyHubUiState state)
    {
        FactionTasksList.RemoveAllChildren();

        if (state.FactionTasks.Count == 0)
        {
            FactionTasksList.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-faction-tasks-none"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        foreach (var task in state.FactionTasks)
        {
            var card = new PanelContainer
            {
                StyleClasses = { "AngleRect" },
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
            };

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(6),
            };

            var details = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            details.AddChild(new Label
            {
                Text = task.Title,
                HorizontalExpand = true,
                ClipText = true,
            });

            var assignee = task.AssigneeName ?? Loc.GetString("pipboy-faction-task-unassigned");
            var status = task.Completed
                ? Loc.GetString("pipboy-faction-task-status-complete")
                : Loc.GetString("pipboy-faction-task-status-open");
            details.AddChild(new Label
            {
                Text = $"[{status}] {assignee}",
                StyleClasses = { "LabelSubText" },
                ClipText = true,
            });

            row.AddChild(details);

            var toggleButton = new Button
            {
                Text = task.Completed
                    ? Loc.GetString("pipboy-faction-task-reopen")
                    : Loc.GetString("pipboy-faction-task-complete"),
                MinSize = new Vector2(72, 0),
                Margin = new Thickness(4, 0, 0, 0),
            };
            var taskId = task.Id;
            toggleButton.OnPressed += _ => OnSendMessage?.Invoke(
                PipBoyHubMessageType.FactionToggleTask,
                null,
                null,
                taskId.ToString());
            row.AddChild(toggleButton);

            card.AddChild(row);
            FactionTasksList.AddChild(card);
        }
    }

    private string GetStateText(MobState state)
    {
        return state switch
        {
            MobState.Alive => Loc.GetString("pipboy-faction-state-ok"),
            MobState.SoftCritical => Loc.GetString("pipboy-faction-state-injured"),
            MobState.Critical => Loc.GetString("pipboy-faction-state-downed"),
            MobState.Dead => Loc.GetString("pipboy-faction-state-dead"),
            _ => Loc.GetString("pipboy-faction-state-unknown"),
        };
    }

    private string GetMemberStatusLine(PipBoyFactionMember member)
    {
        var stateText = GetStateText(member.State);

        if (member.IsOnline)
            return $"{stateText}  {Loc.GetString("pipboy-faction-location-label")}: {member.LocationName}";

        return $"{Loc.GetString("pipboy-faction-state-offline")}  {Loc.GetString("pipboy-faction-location-label")}: {member.LocationName}  {Loc.GetString("pipboy-faction-last-seen-label")}: {member.LastSeenAt:hh\\:mm}";
    }
}
